export const GET_POKEMON_TYPES_SUCCESS = 'GET_POKEMON_TYPES_SUCCESS';
export const GET_POKEMON_BY_TYPES_SUCCESS = 'GET_POKEMON_BY_TYPES_SUCCESS';
export const GET_POKEMON_BY_TYPES_REQUEST = 'GET_POKEMON_BY_TYPES_REQUEST';